/*
 Navicat Premium Data Transfer

 Source Server         : Local
 Source Server Type    : MySQL
 Source Server Version : 100803
 Source Host           : localhost:3306
 Source Schema         : test_hpam

 Target Server Type    : MySQL
 Target Server Version : 100803
 File Encoding         : 65001

 Date: 06/01/2023 16:14:57
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for category_merk
-- ----------------------------
DROP TABLE IF EXISTS `category_merk`;
CREATE TABLE `category_merk` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(25) DEFAULT NULL,
  `slug` varchar(25) DEFAULT NULL,
  `description` varchar(100) DEFAULT NULL,
  `status` tinyint(4) unsigned DEFAULT NULL COMMENT '1=aktif, 2=tidak aktif',
  `updated_by` int(11) unsigned DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of category_merk
-- ----------------------------
BEGIN;
INSERT INTO `category_merk` (`id`, `name`, `slug`, `description`, `status`, `updated_by`, `updated_on`) VALUES (1, 'Samsung', 'samsung', 'merk samsung', 1, NULL, NULL);
INSERT INTO `category_merk` (`id`, `name`, `slug`, `description`, `status`, `updated_by`, `updated_on`) VALUES (2, 'Apple', 'apple', 'merk Apple', 1, NULL, NULL);
COMMIT;

-- ----------------------------
-- Table structure for product
-- ----------------------------
DROP TABLE IF EXISTS `product`;
CREATE TABLE `product` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `id_category` int(11) unsigned DEFAULT NULL,
  `id_category_brand` int(11) unsigned DEFAULT NULL COMMENT 'fk to category, with type=5 ',
  `warna` varchar(100) NOT NULL,
  `variant` varchar(50) DEFAULT NULL,
  `tipe_produk` int(11) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `description2` text DEFAULT NULL,
  `slug` varchar(100) DEFAULT NULL,
  `image` varchar(100) DEFAULT NULL,
  `status` smallint(6) DEFAULT NULL COMMENT '0=unpublish, 1=publish',
  `price` int(11) unsigned DEFAULT NULL,
  `stock` int(11) unsigned NOT NULL DEFAULT 0,
  `weight` float NOT NULL DEFAULT 0,
  `created_by` int(11) unsigned DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `view` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_decms_product_decms_product_category_1` (`id_category`),
  KEY `fk_decms_product_decms_users_1` (`created_by`),
  KEY `fk_decms_product_decms_slug1` (`slug`),
  KEY `created_on` (`created_on`),
  KEY `id_category_brand` (`id_category_brand`),
  KEY `status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of product
-- ----------------------------
BEGIN;
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (1, 'Samsung s21', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21', '2db0a96b-6a4a-4e4b-9a3c-7baa734d8295.jpg', 1, 16000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (2, 'Samsung s21 plus', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21-plus', '80e4430e-57c5-4c78-9a5f-1aba5a82aa01.jpg', 1, 18000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (3, 'Apple iPhone 13 ', 3, 2, 'Blue', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', '<p>Isi Kotak :<br />\n&bull; iPhone dengan iOS 15.<br />\n&bull; Kabel USB-C ke Lightning.<br />\n&bull; Buku Manual dan dokumentasi lain.<br />\n<br />\nNewpack / Slimpack:<br />\nIsi box : Hanya unit dan kabel Type C to lighting (Adaptor dan Earphone belum include)</p>\n', 'samsung-s21-plus', 'fc91f2c3-e8c9-4e22-ab9e-f6c2ba1399d2.jpg', 1, 14225000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (4, 'Apple iPhone 11', 3, 2, 'Black', NULL, 2, NULL, '<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n', NULL, '3071296_fb5dd186-7b43-49a0-9d63-c1ed124f7db7_720_720.jpg', 1, 9649000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (5, 'Samsung s21', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21', '2db0a96b-6a4a-4e4b-9a3c-7baa734d8295.jpg', 1, 16000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (6, 'Samsung s21 plus', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21-plus', '80e4430e-57c5-4c78-9a5f-1aba5a82aa01.jpg', 1, 18000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (7, 'Apple iPhone 13 ', 3, 2, 'Blue', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', '<p>Isi Kotak :<br />\n&bull; iPhone dengan iOS 15.<br />\n&bull; Kabel USB-C ke Lightning.<br />\n&bull; Buku Manual dan dokumentasi lain.<br />\n<br />\nNewpack / Slimpack:<br />\nIsi box : Hanya unit dan kabel Type C to lighting (Adaptor dan Earphone belum include)</p>\n', 'samsung-s21-plus', 'fc91f2c3-e8c9-4e22-ab9e-f6c2ba1399d2.jpg', 1, 14225000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (8, 'Apple iPhone 11', 3, 2, 'Black', NULL, 2, NULL, '<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n', NULL, '3071296_fb5dd186-7b43-49a0-9d63-c1ed124f7db7_720_720.jpg', 1, 9649000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (9, 'Samsung s21', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21', '2db0a96b-6a4a-4e4b-9a3c-7baa734d8295.jpg', 1, 16000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (10, 'Samsung s21 plus', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21-plus', '80e4430e-57c5-4c78-9a5f-1aba5a82aa01.jpg', 1, 18000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (11, 'Apple iPhone 13 ', 3, 2, 'Blue', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', '<p>Isi Kotak :<br />\n&bull; iPhone dengan iOS 15.<br />\n&bull; Kabel USB-C ke Lightning.<br />\n&bull; Buku Manual dan dokumentasi lain.<br />\n<br />\nNewpack / Slimpack:<br />\nIsi box : Hanya unit dan kabel Type C to lighting (Adaptor dan Earphone belum include)</p>\n', 'samsung-s21-plus', 'fc91f2c3-e8c9-4e22-ab9e-f6c2ba1399d2.jpg', 1, 14225000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (12, 'Apple iPhone 11', 3, 2, 'Black', NULL, 2, NULL, '<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n', NULL, '3071296_fb5dd186-7b43-49a0-9d63-c1ed124f7db7_720_720.jpg', 1, 9649000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (13, 'Samsung s21', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21', '2db0a96b-6a4a-4e4b-9a3c-7baa734d8295.jpg', 1, 16000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (14, 'Samsung s21 plus', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21-plus', '80e4430e-57c5-4c78-9a5f-1aba5a82aa01.jpg', 1, 18000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (15, 'Apple iPhone 13 ', 3, 2, 'Blue', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', '<p>Isi Kotak :<br />\n&bull; iPhone dengan iOS 15.<br />\n&bull; Kabel USB-C ke Lightning.<br />\n&bull; Buku Manual dan dokumentasi lain.<br />\n<br />\nNewpack / Slimpack:<br />\nIsi box : Hanya unit dan kabel Type C to lighting (Adaptor dan Earphone belum include)</p>\n', 'samsung-s21-plus', 'fc91f2c3-e8c9-4e22-ab9e-f6c2ba1399d2.jpg', 1, 14225000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (16, 'Apple iPhone 11', 3, 2, 'Black', NULL, 2, NULL, '<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n', NULL, '3071296_fb5dd186-7b43-49a0-9d63-c1ed124f7db7_720_720.jpg', 1, 9649000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (17, 'Samsung s21', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21', '2db0a96b-6a4a-4e4b-9a3c-7baa734d8295.jpg', 1, 16000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (18, 'Samsung s21 plus', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21-plus', '80e4430e-57c5-4c78-9a5f-1aba5a82aa01.jpg', 1, 18000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (19, 'Apple iPhone 13 ', 3, 2, 'Blue', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', '<p>Isi Kotak :<br />\n&bull; iPhone dengan iOS 15.<br />\n&bull; Kabel USB-C ke Lightning.<br />\n&bull; Buku Manual dan dokumentasi lain.<br />\n<br />\nNewpack / Slimpack:<br />\nIsi box : Hanya unit dan kabel Type C to lighting (Adaptor dan Earphone belum include)</p>\n', 'samsung-s21-plus', 'fc91f2c3-e8c9-4e22-ab9e-f6c2ba1399d2.jpg', 1, 14225000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (20, 'Apple iPhone 11', 3, 2, 'Black', NULL, 2, NULL, '<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n', NULL, '3071296_fb5dd186-7b43-49a0-9d63-c1ed124f7db7_720_720.jpg', 1, 9649000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (21, 'Samsung s21', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21', '2db0a96b-6a4a-4e4b-9a3c-7baa734d8295.jpg', 1, 16000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (22, 'Samsung s21 plus', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21-plus', '80e4430e-57c5-4c78-9a5f-1aba5a82aa01.jpg', 1, 18000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (23, 'Apple iPhone 13 ', 3, 2, 'Blue', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', '<p>Isi Kotak :<br />\n&bull; iPhone dengan iOS 15.<br />\n&bull; Kabel USB-C ke Lightning.<br />\n&bull; Buku Manual dan dokumentasi lain.<br />\n<br />\nNewpack / Slimpack:<br />\nIsi box : Hanya unit dan kabel Type C to lighting (Adaptor dan Earphone belum include)</p>\n', 'samsung-s21-plus', 'fc91f2c3-e8c9-4e22-ab9e-f6c2ba1399d2.jpg', 1, 14225000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (24, 'Apple iPhone 11', 3, 2, 'Black', NULL, 2, NULL, '<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n', NULL, '3071296_fb5dd186-7b43-49a0-9d63-c1ed124f7db7_720_720.jpg', 1, 9649000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (25, 'Samsung s21', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21', '2db0a96b-6a4a-4e4b-9a3c-7baa734d8295.jpg', 1, 16000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (26, 'Samsung s21 plus', 3, 1, 'Black', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', 'test', 'samsung-s21-plus', '80e4430e-57c5-4c78-9a5f-1aba5a82aa01.jpg', 1, 18000000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (27, 'Apple iPhone 13 ', 3, 2, 'Blue', NULL, 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et, dolorem! Veritatis, nostrum quis culpa qui quibusdam non dolorem tempora eligendi voluptatum iure ad libero quo fugiat vel nobis sint unde!', '<p>Isi Kotak :<br />\n&bull; iPhone dengan iOS 15.<br />\n&bull; Kabel USB-C ke Lightning.<br />\n&bull; Buku Manual dan dokumentasi lain.<br />\n<br />\nNewpack / Slimpack:<br />\nIsi box : Hanya unit dan kabel Type C to lighting (Adaptor dan Earphone belum include)</p>\n', 'samsung-s21-plus', 'fc91f2c3-e8c9-4e22-ab9e-f6c2ba1399d2.jpg', 1, 14225000, 100, 1, NULL, NULL, 0);
INSERT INTO `product` (`id`, `name`, `id_category`, `id_category_brand`, `warna`, `variant`, `tipe_produk`, `description`, `description2`, `slug`, `image`, `status`, `price`, `stock`, `weight`, `created_by`, `created_on`, `view`) VALUES (28, 'Apple iPhone 11', 3, 2, 'Black', NULL, 2, NULL, '<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n<p>Spesifikasi :<br />\n<br />\nJaringan GSM / HSPA / LTE<br />\nSistem Operasi iOS 14<br />\nProsesor Apple A13 Bionic (7 nm+), Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)<br />\nGPU Apple GPU (4-core graphics)<br />\nRAM 4 GB<br />\nUkuran Layar 6.1 inch<br />\nTipe Layar Liquid Retina IPS LCD capacitive touchscreen, 16M colors, True Tone, Haptic Touch, 625 nits<br />\nResolusi Layar 828 x 1792 pixels, 19.5:9 ratio (~326 ppi density)<br />\nKamera Belakang<br />\nDual 12 MP, f/1.8, 26mm (wide), 1/2.55&quot;, 1.4&micro;m, dual pixel PDAF, OIS<br />\n12 MP, f/2.4, 13mm (ultrawide)<br />\n<br />\nKamera Depan<br />\n12 MP, f/2.2, 23mm (wide)<br />\nSL 3D camera<br />\n<br />\nAudio Stereo Speakers, Dolby Atmos, Dolby Digital Plus<br />\nWLAN Wi-Fi 802.11 a/b/g/n/ac/ax, dual-band, hotspot<br />\nBluetooth 5.0, A2DP, LE<br />\nGPS A-GPS, GLONASS, GALILEO, QZSS<br />\nSensor Face ID, accelerometer, gyro, proximity, compass, barometer, Proximity, Ambient light, Siri natural language commands and dictation<br />\nBaterai 3110 mAh<br />\nPengisian Daya Support fast battery charging, USB Power Delivery 2.0, Qi wireless charging<br />\nSlot Memori Eksternal No<br />\nBerat 194 gr<br />\nDimensi 150.9 x 75.7 x 8.3 mm</p>\n', NULL, '3071296_fb5dd186-7b43-49a0-9d63-c1ed124f7db7_720_720.jpg', 1, 9649000, 100, 1, NULL, NULL, 0);
COMMIT;

-- ----------------------------
-- Table structure for product_type
-- ----------------------------
DROP TABLE IF EXISTS `product_type`;
CREATE TABLE `product_type` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(25) DEFAULT NULL,
  `slug` varchar(25) DEFAULT NULL,
  `description` varchar(100) DEFAULT NULL,
  `status` tinyint(4) unsigned DEFAULT NULL COMMENT '0=aktif, 1=aktif',
  `updated_by` int(11) unsigned DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of product_type
-- ----------------------------
BEGIN;
INSERT INTO `product_type` (`id`, `name`, `slug`, `description`, `status`, `updated_by`, `updated_on`) VALUES (1, 'Audio', 'audio', 'Product audio', 1, NULL, NULL);
INSERT INTO `product_type` (`id`, `name`, `slug`, `description`, `status`, `updated_by`, `updated_on`) VALUES (2, 'Smartphone', 'smartphone', 'Product Smartphone', 1, NULL, NULL);
INSERT INTO `product_type` (`id`, `name`, `slug`, `description`, `status`, `updated_by`, `updated_on`) VALUES (3, 'Gadget', 'gadget', 'Product Gadget', 1, NULL, NULL);
INSERT INTO `product_type` (`id`, `name`, `slug`, `description`, `status`, `updated_by`, `updated_on`) VALUES (4, 'Accessories', 'accessories', 'Product Accessories', 1, NULL, NULL);
COMMIT;

-- ----------------------------
-- Table structure for t_category
-- ----------------------------
DROP TABLE IF EXISTS `t_category`;
CREATE TABLE `t_category` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_parent` int(11) DEFAULT 0 COMMENT 'fk to self',
  `level` smallint(6) DEFAULT NULL COMMENT 'level of the cat sub cat',
  `name` varchar(100) DEFAULT NULL,
  `image` varchar(100) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `slug` varchar(100) DEFAULT NULL,
  `href` varchar(250) DEFAULT NULL,
  `status` smallint(6) DEFAULT NULL COMMENT '1=publish,0=unpublish',
  `display_order` smallint(6) DEFAULT 0 COMMENT 'display order',
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) unsigned DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `updated_by` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_decms_category_decms_users_1` (`created_by`),
  KEY `fk_decms_category_decms_users_2` (`updated_by`),
  KEY `fk_decms_category_slug_1` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of t_category
-- ----------------------------
BEGIN;
INSERT INTO `t_category` (`id`, `id_parent`, `level`, `name`, `image`, `description`, `slug`, `href`, `status`, `display_order`, `created_on`, `created_by`, `updated_on`, `updated_by`) VALUES (1, 1, 1, 'Promo Bank', NULL, 'Promo Bank', 'Promo-Bank', NULL, 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO `t_category` (`id`, `id_parent`, `level`, `name`, `image`, `description`, `slug`, `href`, `status`, `display_order`, `created_on`, `created_by`, `updated_on`, `updated_by`) VALUES (2, 1, 1, 'Promo Bank BCA', NULL, 'Promo Bank BCA', 'Promo-Bank-BCA', NULL, 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO `t_category` (`id`, `id_parent`, `level`, `name`, `image`, `description`, `slug`, `href`, `status`, `display_order`, `created_on`, `created_by`, `updated_on`, `updated_by`) VALUES (3, 3, 1, 'Samsung S Series', NULL, 'Product Samsung S Series', 'Samsung-S-Series', NULL, 1, 0, NULL, NULL, NULL, NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
